extend type HealthGoal {
  """
  ✨ Implicit primary key field. It's a UUID column default to a generated new value. See `@table` for how to customize it.
  """
  id: UUID! @default(expr: "uuidV4()") @fdc_generated(from: "HealthGoal", purpose: IMPLICIT_KEY_FIELD)
  """
  ✨ Implicit foreign key field based on `HealthGoal`.`metricType`. It must match the value of `HealthMetricType`.`id`. See `@ref` for how to customize it.
  """
  metricTypeId: UUID! @fdc_generated(from: "HealthGoal.metricType", purpose: IMPLICIT_REF_FIELD)
  """
  ✨ Implicit foreign key field based on `HealthGoal`.`user`. It must match the value of `User`.`id`. See `@ref` for how to customize it.
  """
  userId: UUID! @fdc_generated(from: "HealthGoal.user", purpose: IMPLICIT_REF_FIELD)
}
extend type HealthMetricRecord {
  """
  ✨ Implicit primary key field. It's a UUID column default to a generated new value. See `@table` for how to customize it.
  """
  id: UUID! @default(expr: "uuidV4()") @fdc_generated(from: "HealthMetricRecord", purpose: IMPLICIT_KEY_FIELD)
  """
  ✨ Implicit foreign key field based on `HealthMetricRecord`.`metricType`. It must match the value of `HealthMetricType`.`id`. See `@ref` for how to customize it.
  """
  metricTypeId: UUID! @fdc_generated(from: "HealthMetricRecord.metricType", purpose: IMPLICIT_REF_FIELD)
  """
  ✨ Implicit foreign key field based on `HealthMetricRecord`.`user`. It must match the value of `User`.`id`. See `@ref` for how to customize it.
  """
  userId: UUID! @fdc_generated(from: "HealthMetricRecord.user", purpose: IMPLICIT_REF_FIELD)
}
extend type HealthMetricType {
  """
  ✨ Implicit primary key field. It's a UUID column default to a generated new value. See `@table` for how to customize it.
  """
  id: UUID! @default(expr: "uuidV4()") @fdc_generated(from: "HealthMetricType", purpose: IMPLICIT_KEY_FIELD)
}
extend type ProviderAccess {
  """
  ✨ Implicit primary key field. It's a UUID column default to a generated new value. See `@table` for how to customize it.
  """
  id: UUID! @default(expr: "uuidV4()") @fdc_generated(from: "ProviderAccess", purpose: IMPLICIT_KEY_FIELD)
  """
  ✨ Implicit foreign key field based on `ProviderAccess`.`user`. It must match the value of `User`.`id`. See `@ref` for how to customize it.
  """
  userId: UUID! @fdc_generated(from: "ProviderAccess.user", purpose: IMPLICIT_REF_FIELD)
}
extend type User {
  """
  ✨ Implicit primary key field. It's a UUID column default to a generated new value. See `@table` for how to customize it.
  """
  id: UUID! @default(expr: "uuidV4()") @fdc_generated(from: "User", purpose: IMPLICIT_KEY_FIELD)
}
